---
title: "Resume"
output: 
  html_document
---
<head>
<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-Y1G4CR6XYK"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-Y1G4CR6XYK');
</script>
</head>

A PDF copy can be downloaded [here](./files/adeline_shin_resume.pdf).

## Education

**Columbia Mailman School of Public Health**, New York, NY: 2019-2021 <br>
M.S. Candidate in Biostatistics, Theory and Methods Track <br>
GPA: 3.51/4.00

**Carnegie Mellon University**, Pittsburgh, PA: 2015-2019 <br>
B.S. in Chemical Engineering with University Honors <br>
Additional Major in Biomedical Engineering, Minor in Drama <br> 
GPA: 3.52/4.00

## Work Experience
**Humana**, Boston, MA <br>
*Data Scientist 2*: June 2021-Present <br>

* Led study design and opportunity sizing of populations for new clinical programs to improve health and create enterprise value for over 200,000 members
* Designed and analyzed outcomes of Social Needs pilots that have helped over 500,000 members with social needs such as food insecurity and loneliness; determined through survey results and claims data to determine whether pilot should be expanded or not
* Led novel analysis measuring value of a digital product by matching member results with internal claims data, working with product managers and external vendors; Humana award recognition given for this analysis

*Graduate Analytics Intern*: May 2020-May 2021 <br>

* Provided insight on member participation and pilot study results for food insecurity programs for members facing social determinants of health issues
* Designed lifetime value model to prioritize customer contact and expand Humana Pharmacy benefit to vulnerable populations
* Won inaugural Digital Health & Analytics (DH&A) Team Hackathon with a product for Humana members for the next pandemic

**New York City Department of Health and Mental Hygiene**: June-August 2018 <br>
*HRTP Intern, Division of Informatics*

* Cleaned National Provider Index (NPI) data warehouse of 50 million rows for widespread, transparent use within agency
* Condensed NPI database to relevant data using exploratory data analysis to filter out repeated and unnecessary values
* Independently learned SQL to program a stored procedure that updates the NPI database weekly

**Eli Lilly and Company**, San Diego, CA <br>
*Protein Purification Intern*: June-August 2017

* Investigated new purification scheme nominated as one of Eli Lilly's Top 100 Innovations of 2017
* Obtained results for 3 new protein structures as a result of prot-A and IMAC purification

*Protein Crystallization Intern*: May-August 2016 <br>

* Applied high-throughput crystallization of proteins to multiple projects, leading to discovery of 2 unique protein structures

**University of Pittsburgh Medical Center**: September 2015-March 2016 <br>
*Emergency Department Volunteer*

* Aided patients and nurses in Emergency Department, making rounds and offering supplies to benefit patients

## Projects
[**Formulae One**](fone.html) <br>

* Predictive Modeling of Formula One race results
* Visualization of lap times and driver differences
* Website building using Dash and Python, deployment with Heroku

[**COVID-19 Modeling and Visualization**](covid19.html) <br>

* Coordinate-Wise Optimization
* Creative Visualization with Stratification
* K-Means and Gaussian Mixture Modeling Clustering

[**Taxi Habits of New Yorkers on Valentine's Day**](nyctaxis.html) <br>

* Data Display on Geographic Maps using Plotly
* Shiny Dashboards
* Rmd Website Creation

[**Medtronic Scoliosis Simulator**](medtronic.Rmd) <br>

* Engineering Prototyping
* 3D-Printing and Manufacturing
* Consumer Product Design

[**ChocLine Printer**](chocline.html) <br>

* Optimization of Fluid Dynamic Parameters
* Engineering Design

## Leadership
**Society of Women Engineers (SWE)**: Mentoring Chair <br>

* Connected over 90 mentors and mentees as CMU SWE's mentoring chair, growing the program by over 50%
* Organized and hosted events related to personal and professional development

## Skills
**Technical**: **Python**, **PySpark**, **R**, **SAS**, **LaTeX**, GitHub, Website Creation, **SQL**, **MATLAB**, Microsoft Office Suite, ASPEN, CAD, 3D-Printing, Laser Cutting, Prototyping, Consumer Product Design <br>
**Languages**: English, Conversational Mandarin
