---
title: "Interactive Plots"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(p8105.datasets)
library(plotly)
```


```{r data_tidying, include = FALSE}
data("instacart")
instacart_data = instacart %>% 
  janitor::clean_names()
```

-----------------------------------------------------------------------

### Chart A

```{r}
aisle_data = 
  instacart_data %>% 
  count(aisle_id)

aisle_ggplot =
  aisle_data %>% 
    subset(n > 10000) %>% 
    ggplot(aes(x = aisle_id, y = n)) +
    geom_col() +
    labs(
      title = "Number of Items Ordered in Each Aisle",
      x = "Aisle Number",
      y = "Number of Items Ordered",
      caption = "Only aisles with over 10,000 items shown"
    )

ggplotly(aisle_ggplot)
```

-----------------------------------------------------------------------

### Chart B

```{r}
order_data = as.data.frame(table(pull(instacart_data, order_hour_of_day))) %>% 
  select("hour" = "Var1", "freq" = "Freq")

order_ggplot = 
  order_data %>% 
    ggplot(aes(x = hour, y = freq)) +
    geom_point(colour = "red", size = 1.5) +
    labs(
      title = "Number of Orders Placed per Hour of Day",
      x = "Hour of Day",
      y = "Number of Orders"
    )

ggplotly(order_ggplot)
```

### Chart C

```{r}
dept_data =
  instacart_data %>% 
  select(order_id, department) %>% 
  group_by(order_id) %>% 
  count(department) %>% 
  filter(department != "missing")
  
dept_ggplot =
  dept_data %>% 
  ggplot(aes(x = department, y = n)) +
  geom_boxplot() +
  labs(
    title = "Number of Items Ordered in Each Department Per Order",
    x = "Department",
    y = "Number of Items Ordered in an Order"
  ) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))

ggplotly(dept_ggplot)
```

